<a href="https://colab.research.google.com/github/ananthavarshinireddy123-ai/Varshani-Reddy/blob/main/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
arr1=([1,2,3,4])
arr2=([5,6,4,7])
print(arr1)
ar=np.array([1,2,3,4])
print(ar)
zero=np.zeros((2,3))
print(zero)
one=np.ones((4,5))
print(one)
line=np.linspace(1,3,5)
print(line)
id=np.eye(4,4)
print(id)
randnum=((np.random.rand(2,3)))
print(randnum)
ashp=np.shape(arr2)
print(ashp)

arr=np.arange(2,10).reshape(4,2)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1.  1.5 2.  2.5 3. ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.89676528 0.61559726 0.92282437]
 [0.2169768  0.60543197 0.57060449]]
(4,)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]


In [13]:
# Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

#Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr - 5)
print("Array squared:", arr ** 2)

#Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

#Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

#Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]
